skillMetadata:
  sections:
    - name: Connection
      fields:
        - name: host
          type: text
          label: Host
          value: ''
        - name: port
          type: number
          label: Port
          value: 1883
        - name: username
          type: text
          label: Username
          value: ''
        - name: password
          type: text
          label: Password
          value: ''
        - name: subtopic
          type: text
          label: Subtopic
          value: ''
    - name: Discovery
      fields:
        - name: advertise_sensors
          type: checkbox
          label: Advertise available sensors to home automation server
          value: 'true'
        - name:  discovery_prefix
          type: text
          label: Discovery topic prefix
          value: 'homeassistant'
          
          
